---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 14758.
--- DateTime: 2023/9/6 18:53
---
for i =10 ,20,3 do
    --print(i)
end

function f(x)
    print("function")
    return x*2
end

for i=1,f(1) do print(i)
end

a= string.find("www.runoob.com", "runoob")
print(a)

function fwrite(fmt, ...)  ---> 固定的参数fmt
return io.write(string.format(fmt, ...))
end

fwrite("%d runoobd\n" ,1)       --->fmt = "runoob", 没有变长参数。
fwrite("%d%d\n", 1, 2,3)   --->fmt = "%d%d", 变长参数为 1 和 2

