---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 14758.
--- DateTime: 2023/9/6 18:53
---
for i =10 ,20,3 do
    --print(i)
end

function f(x)
    print("function")
    return x*2
end

for i=1,f(1) do print(i)
end

a= string.find("www.runoob.com", "runoob")
print(a)

