---
--- Generated by Luanalysis
--- Created by pore.
--- DateTime: 2023-09-10 12:26
---
mytable={}
print("mytable 的类型是 ",type(mytable))


mytable[1]= "d"
mytable[2]= "b"
mytable[3]= "c"
mytable["a"]='a'
mytable[14]='x'

for i, v in ipairs(mytable) do
    print(i..v)
end

print('------------')
--table.remove(mytable)
for i, v in pairs(mytable) do
    print(v)
end
print(#mytable)


