---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 14758.
--- DateTime: 2023/9/6 17:18
---
a = 5               -- 全局变量
local b = 5         -- 局部变量

do
    local a = 6     -- 局部变量
    --b = 6           -- 对局部变量重新赋值
    print(a,b);     --> 6 6
end

print(a,b)      --> 5
function test1()
    a = "hello" .. "world"
    a, b = 10, 2*1
    print(a,b)
end

-- 定义一个返回两个值的函数
function f()
    return 10, 20
end

-- 调用函数并将返回的值分配给变量a和b
local a, b = f()
print(a,b)